# Generated by Django 4.0.6 on 2022-07-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('shopName', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=128)),
                ('star', models.IntegerField(default=0)),
                ('comment', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shoppic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('URL', models.TextField()),
                ('shopId', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='crawling.shopinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Shopmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('menu', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=128)),
                ('shopId', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='crawling.shopinfo')),
            ],
        ),
    ]
