# Generated by Django 4.0.6 on 2022-07-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('crawling', '0002_alter_shopmenu_shopid_alter_shoppic_shopid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=128)),
                ('star', models.IntegerField(default=0)),
                ('shopId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawling.shopinfo')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
