# Generated by Django 4.0.6 on 2022-07-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('crawling', '0002_alter_shopmenu_shopid_alter_shoppic_shopid'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='shopId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crawling.shopinfo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user'),
        ),
    ]
